config/routes.rb
Rails.application.routes.draw do
  root "items#index"
  
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  } 
   
  devise_scope :user do
    get 'users/confirmation' => 'users/registrations#confirmation'
  end

  resources :users do
    collection do
      get :logout, :like
    end
  end
  resources :items do
    collection do
      get :search
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
      get :header_category, defaults: { format: 'json' }
    end
    resource :likes, only: [:create, :destroy]
    resources :purchases do
      collection do
        get :purchase, :after_purchase
      end
    end
    member do
      get :image_delete
    end
  end
  resources :cards do
    collection do
      get :delete
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
  has_many :destinations
  has_one :card
  has_many :likes
  has_many :comments

  accepts_nested_attributes_for :destinations 
  validates_associated :destinations

  domein = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  hiragana = /\A[ぁ-んー－]+\z/
  zennkaku = /\A[ぁ-んァ-ン一-龥]/

  validates :nickname, presence: true
  validates :email, presence: true, format: { with:  domein }, uniqueness: true
  validates :password, presence: true, length: { minimum: 7 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true
  validates :family_name, presence: true, format: { with:  zennkaku }
  validates :first_name, presence: true, format: { with:  zennkaku }
  validates :family_name_kana, presence: true, format: { with:  hiragana }
  validates :first_name_kana, presence: true, format: { with:  hiragana }
  validates :birthday, presence: true
  

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :set_hash, only: [:new, :create]
  
  # GET /resource/sign_up
  def new
    @user = User.new
    @destination = @user.destinations.new
  end

  # POST /resource
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_confirmation_path
      flash[:notice] = "ログインに成功しました"
      sign_in(@user)
    else
      flash[:alert] = "登録されませんでした"
      render :new
    end   
  end
  
  def confirmation
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :nickname, :family_name, :first_name, :family_name_kana, :first_name_kana, :birthday, destinations_attributes: [:family_name, :first_name, :family_name_kana, :first_name_kana, :postal_code, :prefecture_id, :city, :address, :after_address, :phone, user_id: current_user])
  end

  def set_hash
    @prefectures = Prefecture.all
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.


  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :header_category_parent, only: [:show, :logout, :like]
  
  def index
    redirect_to new_user_registration_path
  end

  def show
  end

  def logout
  end

  def like
    @items = Item.includes(:likes).where(likes: {user_id: current_user})    
  end

  def header_category_parent
    @header_category_parent = Category.roots
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_footer.html.haml
.footer
  .footer__contents1
    %ul.footer__contents1__rule
      %ul.footer__contents1__rule__num1
        = link_to "#" do
          プライバシーポリシー
      %ul.footer__contents1__rule__num2
        = link_to "#" do
          FURIMA利用規約
      %ul.footer__contents1__rule__num3
        = link_to "#" do
          特定商取引に関する表記
  .footer__contents2
    = link_to "#", id:"logo" do
      = image_tag "logo/logo-white.png", class: 'footer__contents2__footerlogo'
  %p.footer__contents3
    ©︎FURIMA

app/views/users/_header.html.haml
.header
  = link_to root_path, id:"logo" do
    = image_tag "logo/logo.png", class: 'header-logo'

app/views/users/_left-content.html.haml
.left-content
  %nav.mypage-navi
    = link_to user_path(current_user) do
      %li.mypage-nav-head
        マイページ
        .arrow-right.icon-black
    %li.mypage-nav-list
      お知らせ
      .arrow-right.icon
    %li.mypage-nav-list
      やることリスト
      .arrow-right.icon
    = link_to like_users_path do
      %li.mypage-nav-list
        お気に入りリスト
        .arrow-right.icon
    %li.mypage-nav-list
      いいね！一覧
      .arrow-right.icon
    %li.mypage-nav-list
      出品した商品 - 出品中
      .arrow-right.icon
    %li.mypage-nav-list
      出品した商品 - 取引中
      .arrow-right.icon
    %li.mypage-nav-list
      出品した商品 - 売却済み
      .arrow-right.icon
    %li.mypage-nav-list
      購入した商品 - 取引中
      .arrow-right.icon
    %li.mypage-nav-list
      購入した商品 - 過去の取引
      .arrow-right.icon
    %li.mypage-nav-list
      ガイド
      .arrow-right.icon
    %li.mypage-nav-list
      お問い合わせ
      .arrow-right.icon
    .mypage-nav-setting
      設定
    %li.mypage-nav-list
      プロフィール
      .arrow-right.icon
    %li.mypage-nav-list
      発送元・お届け先住所変更
      .arrow-right.icon
    = link_to cards_path do
      %li.mypage-nav-list
        クレジットカード登録/変更
        .arrow-right.icon
    %li.mypage-nav-list
      メール/パスワード
      .arrow-right.icon
    %li.mypage-nav-list
      本人情報
      .arrow-right.icon
    = link_to logout_users_path do
      %li.mypage-nav-list
        ログアウトページ/ログアウト
        .arrow-right.icon

= link_to new_item_path do
  .exhibit
    %p.exhibit--text
      出品する
    = image_tag "icon/icon_camera.png",class: 'exhibit--image', width: "55px";

app/views/users/like.html.haml
= render "items/header"

.wrapper
  = render "left-content"
  .like_wrapper
    .like-main__name
      お気に入り一覧
    .like-main__contents5
      -unless @items.blank?
        .like-main__contents5__category__lists
          - @items.each do |item|
            = link_to item_path(item) do
              .like-main__contents5__category__lists__list
                .like-main__contents5__category__lists__list__image
                  = image_tag item.images[0].image.to_s, size: '220x150'
                  -if item.buyer_id.present? 
                    .like-main__contents5__category__lists__list__image__sold
                      .like-main__contents5__category__lists__list__image__sold__inner
                        SOLD
                .like-main__contents5__category__lists__list__detail
                  %h8.like-main__contents5__category__lists__list__detail__name
                    = item.name
                  %ul.like-main__contents5__category__lists__list__detail__price
                    %li 
                      = item.price
                      円
                    %li.like
                      ★
                      = item.likes.count
                  %p.like-main__contents5__category__image__detail__tax (税込)
      - else
        .like-main__contents5__category__lists
          登録がありません


= render "items/footer"

app/views/users/logout.html.haml
= render "items/header"

.wrapper
  = render "left-content"
  .logout-content
    = link_to destroy_user_session_path, method: :delete do
      .logout-content__btn
        ログアウト

= render "items/footer"

app/views/users/show.html.haml
= render "items/header"

.wrapper
  = render "left-content"
  .right-content
    .right-content1
      .right-content1__cover
        .right-content1__name
          = current_user.nickname
        .right-content1__exhibit
    .right-content2
      .mypage-tab-container
        .mypage-tabs
          .mypage-tabs__notifidation
            お知らせ
          .mypage-tabs__to-do
            やることリスト
        .tab-content
          .tab-content__not-found
            現在、お知らせはありません
    .right-content3
      .mypage-tab-container
        .mypage-tab-head
          購入した商品
        .mypage-tabs
          .mypage-tabs__transaction-now
            取引中
          .mypage-tabs__transaction-old
            過去の取引
        .tab-content
          .tab-content__not-found
            取引中の商品がありません

= render "items/footer"