config/routes.rb
Rails.application.routes.draw do
  root "items#index"
  
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  } 
   
  devise_scope :user do
    get 'users/confirmation' => 'users/registrations#confirmation'
  end

  resources :users do
    collection do
      get :logout, :like
    end
  end
  resources :items do
    collection do
      get :search
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
      get :header_category, defaults: { format: 'json' }
    end
    resource :likes, only: [:create, :destroy]
    resources :purchases do
      collection do
        get :purchase, :after_purchase
      end
    end
    member do
      get :image_delete
    end
  end
  resources :cards do
    collection do
      get :delete
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/condition.rb
class Condition < ActiveHash::Base
  self.data = [

    {id: 1, name: '新品、未使用'}, {id: 2, name: '未使用に近い'}, {id: 3, name: '目立った傷汚れなし'},
    {id: 4, name: 'やや傷や汚れあり'}, {id: 5, name: '傷や汚れあり'}, {id: 6, name: '全体的に状態が悪い'}

  ]
end

app/models/day.rb
class Day < ActiveHash::Base
  self.data = [

    {id: 1, name: '1-2日で発送'}, { id: 2, name: '2-3日で発送'}, {id: 3, name: '4-7日で発送'}

  ]
end

app/models/delivery_fee.rb
class DeliveryFee < ActiveHash::Base
  self.data = [

    {id: 1, name: '出品者負担'}, {id: 2, name: '購入者負担'}

  ]
end

app/models/delivery_method.rb
class DeliveryMethod < ActiveHash::Base
  self.data = [

    {id: 1, name: 'ゆうパック'}, {id: 2, name: 'ヤマト宅急便'}, {id: 3, name: '佐川急便'}

  ]
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :user

  hiragana = /\A[ぁ-んー－]+\z/
  zennkaku = /\A[ぁ-んァ-ン一-龥]/

  validates :family_name, presence: true, format: { with:  zennkaku }
  validates :first_name, presence: true, format: { with:  zennkaku }
  validates :family_name_kana, presence: true, format: { with:  hiragana }
  validates :first_name_kana, presence: true, format: { with:  hiragana }
  validates :postal_code, presence: true, length: { is: 7}
  validates :prefecture_id, presence: true
  validates :city, presence: true
  validates :address, presence: true
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :item, optional: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :likes
  has_many :comments
  has_many :images, dependent: :destroy
  belongs_to :user, foreign_key: "seller_id"
  belongs_to :category, foreign_key: "category_id"


  accepts_nested_attributes_for :images, allow_destroy: true
  validates_associated :images

  validates :name, presence: true, length: { maximum: 40 }
  validates :explanation, presence: true, length: { maximum: 1000 }
  validates :category_id, :condition_id, :delivery_fee_id, :prefecture_id, :day_id, :delivery_method_id, presence: { message: "を選択してください" }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }

  validates :images, presence: { message: "を登録してください" }

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :condition
  belongs_to_active_hash :delivery_fee
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :day
  belongs_to_active_hash :delivery_method

  def previous
    Item.where("id < ?", self.id).order("id DESC").first
  end

  def next
    Item.where("id > ?", self.id).order("id ASC").first
  end

  def self.search(search)
    Item.where(['name LIKE ?', "%#{search}%"])
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base

  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
  has_many :destinations
  has_one :card
  has_many :likes
  has_many :comments

  accepts_nested_attributes_for :destinations 
  validates_associated :destinations

  domein = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  hiragana = /\A[ぁ-んー－]+\z/
  zennkaku = /\A[ぁ-んァ-ン一-龥]/

  validates :nickname, presence: true
  validates :email, presence: true, format: { with:  domein }, uniqueness: true
  validates :password, presence: true, length: { minimum: 7 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true
  validates :family_name, presence: true, format: { with:  zennkaku }
  validates :first_name, presence: true, format: { with:  zennkaku }
  validates :family_name_kana, presence: true, format: { with:  hiragana }
  validates :first_name_kana, presence: true, format: { with:  hiragana }
  validates :birthday, presence: true
  

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :payjp_key
  before_action :set_user
  before_action :set_item, except: :show

  def index
    @conditions = Condition.find(@item.condition_id)
    @delivery_fees = DeliveryFee.find(@item.delivery_fee_id)
    

    if @user.card
      customer = Payjp::Customer.retrieve(@user.card.customer_id)
      if params[:card_id]
        @cards = customer.cards.retrieve(params[:card_id])
      else
        @cards = customer.cards.data[0]
      end
    end
    @destination = Destination.find(params[:destination_id])
  end

  def show
    if params[:id] == '1'
      customer = Payjp::Customer.retrieve(@user.card.customer_id)
      @cards = customer.cards
    else
      @destinations = Destination.includes(:user).where(users: {id: current_user.id})
    end
  end

  def purchase
    @item.update_attribute(:buyer_id, current_user.id)
    charge = Payjp::Charge.create(
      :amount => @item.price,
      :customer => @user.card.customer_id,
      :card => params[:card_id],
      :currency => 'jpy',
    )
    redirect_to action: :after_purchase
  end

  def after_purchase
  end

  private

  def payjp_key
    require 'payjp'
    Payjp.api_key = Rails.application.credentials.PAYJP[:secret_access_key]
  end

  def set_user
    @user = User.find(current_user.id)
  end

  def set_item
    @item = Item.find(params[:item_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/purchases/after_purchase.html.haml
= render "users/header"

.after_purchase
  .after_purchase__content
    = link_to items_path do
      .after_purchase__content--link
        .after_purchase__content--link--cover
          購入しました
          %br
          トップページへ

= render "users/footer"

app/views/purchases/index.html.haml
= render "users/header"

.purchase
  .purchase__contents
  
    .notifications
      - flash.each do |key, value|
        = content_tag(:div, value, class: key)

    .purchase__contents__name
      購入内容の確認
    .purchase__contents__product
      .purchase__contents__product__image
        = image_tag @item.images[0].image.to_s, size: '80x80'
      .purchase__contents__product__detail
        .purchase__contents__product__detail__name
          = @item.brand
          %br
          = @item.name
          %br
          = @conditions.name
        .purchase__contents__product__detail__price
          .purchase__contents__product__detail__price--send
            配送料 
            = @delivery_fees.name
            （税込）
          .purchase__contents__product__detail__price--tax
            ¥
            = @item.price
        
    .purchase__contents__price
      .purchase__contents__price__sum
        %span.purchase__contents__price__sum__name
          支払い金額
        %span.purchase__contents__price__sum__detail
          ¥
          = @item.price
    .purchase__contents__way
      - if @cards
        .purchase__contents__way__pay
          %span.purchase__contents__way__pay__name 支払い方法
          = link_to item_purchase_path(id: 1, destination_id: params[:destination_id]) do
            .purchase__contents__way__pay__change
              変更する>

        .purchase__contents__way__detail
          %p.purchase__contents__way__detail__credit クレジットカード
          %p.purchase__contents__way__detail__credit
            ************
            = @cards.last4
          %p.purchase__contents__way__detail__credit
            有効期限
            = @cards.exp_month
            \/
            = @cards.exp_year
          %p.credit-campany
            = @cards.brand
          
      - else
        .purchase__contents__way__detail
        = link_to cards_path do
          クレジットカードを登録してください>


    .purchase__contents__delivery
      %ul.purchase__contents__delivery__name
        %span.purchase__contents__delivery__name__send 配送先
        = link_to item_purchase_path(id: 2, card_id: params[:card_id]) do
          .purchase__contents__delivery__name__change
            変更する>
      
      %li.purchase__contents__delivery__detail
        〒
        = @destination.postal_code[0, 3]
        \-
        = @destination.postal_code[3, 8]
      %li.purchase__contents__delivery__detail
        = @destination.prefecture_id
        = @destination.city
        = @destination.address
        = @destination.after_address
      %li.purchase__contents__delivery__detail
        =  @destination.family_name
        =  @destination.first_name
    = form_with url: purchase_item_purchases_path, method: "get", local: true do |form|
      - if @cards
        = form.hidden_field :card_id, value: @cards.id
        = form.hidden_field :destination_id, value: @destination.id
        = form.submit "購入する", class: 'buy__btn';

= render "users/footer"

app/views/purchases/show.html.haml
= render "users/header"

.purchase2
  .purchase__contents2--cover
    .purchase__contents2
      - if params[:id] == '1'
        .purchase__contents2--name
          カード一覧
      - else
        .purchase__contents2--name
          宛先一覧
    - if params[:id] == '1'
      - if @cards
        - @cards.each do |card|
          .purchase_card
            .purchase_card__list
              = link_to item_purchases_path(item_id: params[:item_id], card_id: card.id, destination_id: params[:destination_id]) do
                %span.purchase_card__list__btn
                  　選択　
                .purchase_card__list--number
                  ************
                  = card.last4
                .purchase_card__list--limit
                  = card.exp_month
                  \/
                  = card.exp_year
                .purchase_card__list--brand
                  = card.brand
      - else
        .purchase_card__none
          カードの登録がありません
    - else
      - @destinations.each do |destination|
        .purchase_destination
          .purchase_destination__list
            = link_to item_purchases_path(item_id: params[:item_id], card_id: params[:card_id], destination_id: destination.id) do
              %span.purchase_destination__list__btn
                　選択　
              .purchase_destination__list--postal_code
                〒
                = destination.postal_code[0, 3]
                \-
                = destination.postal_code[3, 8]
              .purchase_destination__list--address
                = destination.prefecture_id
                = destination.city
                = destination.address
                = destination.after_address
              .purchase_destination__list--name
                =  destination.family_name
                =  destination.first_name

= render "users/footer"