config/routes.rb
Rails.application.routes.draw do
  root "items#index"
  
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  } 
   
  devise_scope :user do
    get 'users/confirmation' => 'users/registrations#confirmation'
  end

  resources :users do
    collection do
      get :logout, :like
    end
  end
  resources :items do
    collection do
      get :search
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
      get :header_category, defaults: { format: 'json' }
    end
    resource :likes, only: [:create, :destroy]
    resources :purchases do
      collection do
        get :purchase, :after_purchase
      end
    end
    member do
      get :image_delete
    end
  end
  resources :cards do
    collection do
      get :delete
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :likes
  has_many :comments
  has_many :images, dependent: :destroy
  belongs_to :user, foreign_key: "seller_id"
  belongs_to :category, foreign_key: "category_id"


  accepts_nested_attributes_for :images, allow_destroy: true
  validates_associated :images

  validates :name, presence: true, length: { maximum: 40 }
  validates :explanation, presence: true, length: { maximum: 1000 }
  validates :category_id, :condition_id, :delivery_fee_id, :prefecture_id, :day_id, :delivery_method_id, presence: { message: "を選択してください" }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }

  validates :images, presence: { message: "を登録してください" }

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :condition
  belongs_to_active_hash :delivery_fee
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :day
  belongs_to_active_hash :delivery_method

  def previous
    Item.where("id < ?", self.id).order("id DESC").first
  end

  def next
    Item.where("id > ?", self.id).order("id ASC").first
  end

  def self.search(search)
    Item.where(['name LIKE ?', "%#{search}%"])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_hash, only: [:new, :create, :edit, :update]
  before_action :item_find_params, only: [:show, :destroy, :edit, :update]
  skip_before_action :authenticate_user!, only: :header_category
  before_action :header_category_parent, only: [:index, :show, :search,]

  def index
    @items = Item.all.order("created_at DESC").limit(4)
  end

  def new
    @item = Item.new
    @item.images.new
    9.times { @item.images.build }
    @category_parent_array = Category.where(ancestry: nil)
  end

  def create
    @item = Item.new(item_params)
    @category_parent_array = Category.where(ancestry: nil)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
    9.times { @item.images.build }
    @category = Category.find(@item.category_id)
    if @category.root?
      @parent_category = @category
      @parent_category_array = @parent_category.siblings

      @childern_category_array = @category.children

    elsif @category.ancestors? && @category.children?
      @child_category = @category
      @childern_category_array = @child_category.siblings

      @parent_category = @child_category.parent
      @parent_category_array = @parent_category.siblings

      @grandchildren_category_array = @child_category.children

    else
      @grandchild_category = @category
      @grandchildren_category_array = @grandchild_category.siblings

      @child_category = @grandchild_category.parent
      @childern_category_array = @child_category.siblings

      @parent_category = @child_category.parent      
      @parent_category_array = @parent_category.siblings
    end
  end

  def update
    @item = Item.find(params[:id])
    @category = Category.find(@item.category_id)
    if @category.root?
      @parent_category = @category
      @parent_category_array = @parent_category.siblings

    elsif @category.ancestors? && @category.children?
      @child_category = @category
      @childern_category_array = @child_category.siblings

      @parent_category = @child_category.parent
      @parent_category_array = @parent_category.siblings

    else
      @grandchild_category = @category
      @grandchildren_category_array = @grandchild_category.siblings

      @child_category = @grandchild_category.parent
      @childern_category_array = @child_category.siblings

      @parent_category = @child_category.parent      
      @parent_category_array = @parent_category.siblings
    end
    if @item.update(item_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def image_delete
    image = Image.find(params[:image_id])
    image.destroy
  end

  def show
    @category_parent_show = Category.where(ancestry:nil)
    @category = Category.find(@item.category_id)
    @conditions = Condition.find(@item.condition_id)
    @delivery_fees = DeliveryFee.find(@item.delivery_fee_id)
    @delivery_methods = DeliveryMethod.find(@item.delivery_method_id)
    @prefectures = Prefecture.find(@item.prefecture_id)
    @days = Day.find(@item.day_id)

    destinations = Destination.includes(:user).where(users: {id: current_user})
    @destination = destinations[0]
    if user_signed_in?
      @like = Like.find_by(user_id: current_user.id, item_id: params[:id])
      
    end
  end
  
  def destroy
    if @item.user.id == current_user.id && @item.destroy
      redirect_to root_path, notice: "削除が完了しました"
    else
      redirect_to root_path, alert: "削除が失敗しました"
    end
  end

  def search
    @items = Item.search(params[:search])
  end
 
  def header_category
    @header_category_children = Category.find_by(id: params[:category_id]).children.map { |category| [category[:id], category[:name]] }.to_h
    render json: @header_category_children
  end

  def category_children
    @category_children = Category.find(params[:parent_id] ).children
  end

  def category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end
  
  def header_category_parent
    @header_category_parent = Category.roots
  end
  private
  
  def set_hash
    @conditions = Condition.all
    @delivery_fees = DeliveryFee.all
    @delivery_methods = DeliveryMethod.all
    @prefectures = Prefecture.all
    @days = Day.all
  end

  def item_params
    params.require(:item).permit(:name, :explanation, :brand, :price, :size, :category_id, :condition_id, :delivery_fee_id, :prefecture_id, :day_id, :delivery_method_id, images_attributes: [:image, :_destroy,:id]).merge(seller_id: current_user.id)
  end

  def item_find_params
    @item = Item.find(params[:id]) 
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_error_form.html.haml
- if @item.errors.any?
  .alert
    %ul
      - @item.errors.full_messages_for(culumn).each do |message|
        %li
          = message

app/views/items/_footer.html.haml
.topfooter
  .topfooter__upper
    .topfooter__upper__about
      %ul.topfooter__upper__about--title FURIMAについて
      %li.topfooter__upper__about--list 会社概要(運営会社)
      %li.topooter__upper__about--list プライバシーポリシー
      %li.topfooter__upper__about--list FURIMA規約
      %li.topfooter__upper__about--list ポイントに関する特約
    .topfooter__upper__about
      %ul.topfooter__upper__about--title FURIMAを見る
      %li.topfooter__upper__about--list カテゴリー一覧
      %li.topfooter__upper__about--list ブランド一覧
    .topfooter__upper__about
      %ul.topfooter__upper__about--title FURIMAガイド
      %li.topfooter__upper__about--list FURIMAガイド
      %li.topfooter__upper__about--list FURIMAロゴ利用ガイドライン
      %li.topfooter__upper__about--list お知らせ

  .topfooter__low
    .topfooter__low__logo
      = image_tag "logo/logo-white.png", width: "160px";
    %p.topfooter__low--copyright ©️FURIMA

app/views/items/_header.html.haml
.topheader
  .topheader__lists
    .topheader__lists__upper
      .topheader__lists__upper__name
        = link_to root_path do
          = image_tag "logo/logo.png", size: '140x42';

      .topheader__lists__upper__search
        .topheader__lists__upper__search__input
          = form_with url: search_items_path, local: true, method: :get do |form|
            = form.text_field :search, class: 'topheader__lists__upper__search__input__keyword',placeholder: "キーワードから探す"
            %button.topheader__lists__upper__search__input__btn<>
              = image_tag "icon/icon-search 1.png", size: '20x20';
    .topheader__lists__low
      .topheader__lists__low__select
      
        .topheader-category
          = link_to "カテゴリー", class: "topheader-category__tab"
          .category-list
            %ul.category-list__parent.hide
              - @header_category_parent.each do |category|
                %li.category-list__parent--name{id: "#{category[:id]}"}
                  = category[:name]
            %ul.category-list__children
            %ul.category-list__grandchild

        .topheader__lists__low__select__brand
          =link_to 'ブランド' ,class: "topheader__lists__low__select__brand__tab"
      .topheader__lists__low__user
        - if user_signed_in?
          .topheader__lists__low__user__logout
            = link_to "マイページ", user_path(current_user), class: "topheader__lists__low__user__logout--tab"
        - else
          .topheader__lists__low__user__login
            = link_to "ログイン", new_user_session_path, method: :get, class: "topheader__lists__low__user__login--tab"
          .topheader__lists__low__user__register
            = link_to "新規会員登録", new_user_registration_path, method: :get, class: "topheader__lists__low__user__register--tab"

app/views/items/destroy.html.haml
= render "header"
.contents-destroy
  .contents-destroy__table
    %h1 削除が完了しました。
    = link_to root_path do
      %p トップページに戻る

= render "footer"

app/views/items/index.html.haml
= render "header"

.main
  .main__contents1
    .main__contents1__explain
      %br
      %br
      %h2 人生を変えるフリマアプリ
      .main__contents1__explain__p
        %p FURIMAはだれでもかんたんに出品・購入できる
        %p フリマアプリです。
      .icon
        .icon__App
          = image_tag "logo/google.png", class: 'image-icon', width: "180px";
        .icon__Google
          = image_tag "logo/google.png", class: 'image-icon', width: "180px";

  .main__contents2
    .main__contents2__reasons
      %h2.main__contents2__reasons__reason FURIMAが選ばれる３つの理由
      %ul.main__contents2__reasons__lists
        %li.main__contents2__reasons__lists__list
          .main__contents2__reasons__lists__list__image
            %span.main__contents2__reasons__lists__list__image__num 1
            = image_tag "pict/pict-reason-01.jpg", width: "280px";
          .main__contents2__reasons__lists__list__explain
            %h3.main__contents2__reasons__lists__list__explain__text
              %span.span 3分
              ですぐに出品
            %p.sentence スマホで入力するだけで簡単に出品できる！
        %li.main__contents2__reasons__lists__list
          .main__contents2__reasons__lists__list__image
            %span.main__contents2__reasons__lists__list__image__num 2
            = image_tag "pict/pict-reason-02.jpg", width: "280px";
          .main__contents2__reasons__lists__list__explain
            %h3.main__contents2__reasons__lists__list__explain__text
              %span.span シンプル 
              で使いやすい
            %p.main__contents2__reasons__lists__list__explain__sentence めんどくさい入力は必要なく、検索も購入もスムーズ！

        %li.main__contents2__reasons__lists__list
          .main__contents2__reasons__lists__list__image
            %span.main__contents2__reasons__lists__list__image__num 3
            = image_tag "pict/pict-reason-03.jpg", width: "280px";
          .main__contents2__reasons__lists__list__explain
            %h3.main__contents2__reasons__lists__list__explain__text
              %span.span 手数料 
              業界最安
            %p.sentence 最大3%でお得に出品&購入！

  .main__contents3
    .main__contents3__explain
      %br
      %h4.main__contents3__explain__number1 会員数日本一位
      .main__contents3__explain__p
        %p FURIMAは、フリマアプリで最も人気。
        %p 出品・購入回数も業界最多です！
        %p ほしかったあの商品に出会えるかもしれません。
      .icon
        .icon__App
          = image_tag "logo/google.png", class: 'image-icon', width: "180px";
        .icon__Google
          = image_tag "logo/google.png", class: 'image-icon', width: "180px";

  .main__contents4
    .main__contents4__features
      %h5.main__contents4__features__name FURIMAの特徴
      %ul.main__contents4__features__lists
        %li.main__contents4__features__lists__list
          .main__contents4__features__lists__list__image
            = image_tag "icon/icon-01.png" , width: "180px";
          .main__contents4__features__lists__list__explain
            %h6.main__contents4__features__lists__list__explain__title 簡単に売り買いできる
            %p.main__contents4__features__lists__list__explain__sentence スマホひとつで、いつでもどこでも簡単に出品・購入が可能！

        %li.main__contents4__features__lists__list
          .main__contents4__features__lists__list__image
            = image_tag "icon/icon-03.png", width: "180px";
          .main__contents4__features__lists__list__explain
            %h6.main__contents4__features__lists__list__explain__title 売上金は即日振込みに対応
            %p.main__contents4__features__lists__list__explain__sentence 午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!

        %li.main__contents4__features__lists__list
          .main__contents4__features__lists__list__image
            = image_tag "icon/icon-04.png", width: "180px";
          .main__contents4__features__lists__list__explain
            %h6.main__contents4__features__lists__list__explain__title 様々な支払いに対応
            %p.main__contents4__features__lists__list__explain__sentence お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

  .main__contents5
    .main__contents5__category
      %h7.category-name
        ピックアップカテゴリー
      .category-product
        新規投稿商品
      .main__contents5__category__lists
        - @items.each do |item|
          = link_to item_path(item) do
            .main__contents5__category__lists__list
              .main__contents5__category__lists__list__image

                = image_tag item.images[0].image.url, size: '220x150'
                -if item.buyer_id.present? 
                  .main__contents5__category__lists__list__image__sold
                    .main__contents5__category__lists__list__image__sold__inner
                      SOLD
              .main__contents5__category__lists__list__detail
                %h8.main__contents5__category__lists__list__detail__name
                  = item.name
                %ul.main__contents5__category__lists__list__detail__price
                  %li 
                    = item.price 
                    円
                  %li.like
                    ★
                    = item.likes.count
                %p.main__contents5__category__lists__list__detail__tax (税込)

  .main__contents5
    .main__contents5__category
      .category-name
        ピックアップブランド
      .category-product
        アーカイバ
      .main__contents5__category__lists
        - @items.each do |item|
          = link_to item_path(item) do
            .main__contents5__category__lists__list
              .main__contents5__category__lists__list__image
                = image_tag item.images[0].image.url, size: '220x150'
                -if item.buyer_id.present? 
                  .main__contents5__category__lists__list__image__sold
                    .main__contents5__category__lists__list__image__sold__inner
                      SOLD
              .main__contents5__category__lists__list__detail
                %h8.main__contents5__category__lists__list__detail__name
                  = item.name
                %ul.main__contents5__category__lists__list__detail__price
                  %li 
                    = item.price
                    円
                  %li.like
                    ★
                    = item.likes.count
                %p.main__contents5__category__image__detail__tax (税込)

  .main__contents7
    .main__contents7__download
      %h9.main__contents7__download--upper だれでもかんたん、人生を変えるフリマアプリ
      %li.main__contents7__download--low 今すぐ無料ダウンロード！
      .icon2
        .icon2__App
        = image_tag "logo/google.png", class: 'image-icon', width: "180px";
        .icon2__Google
        = image_tag "logo/google.png", class: 'image-icon', width: "180px";


= render "footer"

= link_to new_item_path do
  .exhibit
    %p.exhibit--text 出品する
    = image_tag "icon/icon_camera.png",class: 'exhibit--image', width: "55px";

app/views/items/new.html.haml
= render "users/header"

.contents
  = form_with model: @item, local: true do |form|
    .new-item-title
      %p 商品の情報を入力
    .new-item-outline
      .input-image
        .input-image__headline
          = form.label :image, "出品画像", class: 'input-image__headline--label'
          %span.input-image__headline--required 必須

          = render "error_form", culumn: :images
        .input-image__comment 
          ファイルを選択をクリックするとアップロードできます
        = form.fields_for :images do |image|
          = image.file_field :image, class: 'input-image__file-field'
          
      .input-name
        .input-name__headline
          = form.label :name, "商品名", class: 'input-name__headline--label'
          %span.input-name__headline--required 必須
          = render "error_form", culumn: :name
        = form.text_field :name, placeholder: "40文字まで", class: 'input-name__text-field'

      .input-explanation
        .input-explanation__headline
          = form.label :explanation, "商品の説明", class: 'input-explanation__headline--label'
          %span.input-explanation__headline--required 必須
          = render "error_form", culumn: :explanation
        = form.text_area :explanation, placeholder: "1,000文字まで\n(色、素材、重さ、定価、注意点など)\n\n例）2015年ごろに3万円で購入したバッグです。ネイビーで傷はありません。", class: 'input-explanation__text-area'


    .new-item-details
      %p.new-item-details__category-name 商品の詳細

      .input-category
        .input-category__headline.new-input-category__headline
          = form.label :category_id, "カテゴリー", class: 'input-category__headline--label'
          %span.input-category__headline--required 必須
          = render "error_form", culumn: :category_id
          = form.collection_select :category_id, @category_parent_array,:id,:name, {prompt: "---"}, {class: 'input-category__select', id: 'item_category_id'}

      .input-brand
        .input-brand__headline
          = form.label :brand, "ブランド", class: 'input-brand__headline--label'
          %span.input-brand__headline--any 任意
        = form.text_field :brand, placeholder: "例）シャネル", class: 'input-brand__text-field'

      .input-size
        .input-size__headline
          = form.label :size, "商品のサイズ", class: 'input-size__headline--label'
          %span.input-size__headline--any 任意
        = form.text_field :size, placeholder: "例）S・M・L、27cmEEE、〇〇cm × 〇〇cm", class: 'input-size__text-field'

      .input-condition
        .input-condition__headline
          = form.label :condition_id, "商品の状態", class: 'input-condition__headline--label'
          %span.input-condition__headline--required 必須
          = render "error_form", culumn: :condition_id
        = form.collection_select(:condition_id, @conditions, :id, :name, {prompt: "選択してください"}, {class: 'input-condition__select'})


    .delivery
      %p.delivery__category-name 配送について

      .input-delivery-fee
        .input-delivery-fee__headline
          = form.label :delivery_fee_id, "配送料の負担", class: 'input-delivery-fee__headline--label'
          %span.input-delivery-fee__headline--required 必須
          = render "error_form", culumn: :delivery_fee_id
        = form.collection_select(:delivery_fee_id, @delivery_fees, :id, :name, {prompt: "選択してください"}, {class: 'input-delivery-fee__select'})

      .input-delivery-method
        .input-delivery-method__headline
          = form.label :delivery_method_id, "配送の方法", class: 'input-delivery-method__headline--label'
          %span.input-delivery-method__headline--required 必須
          = render "error_form", culumn: :delivery_method_id
        = form.collection_select(:delivery_method_id, @delivery_methods, :id, :name, {prompt: "選択してください"}, {class: 'input-delivery-method__select'})

      .input-delivery-prefecture
        .input-delivery-prefecture__headline
          = form.label :prefecture_id, "配送元の地域", class: 'input-delivery-prefecture__headline--label'
          %span.input-delivery-prefecture__headline--required 必須
          = render "error_form", culumn: :prefecture_id
        = form.collection_select(:prefecture_id, @prefectures, :id, :name, {prompt: "選択してください"}, {class: 'input-delivery-prefecture__select'})

      .input-delivery-days
        .input-delivery-days__headline
          = form.label :day_id, "発送までの日数", class: 'input-delivery-days__headline--label'
          %span.input-delivery-days__headline--required 必須
          = render "error_form", culumn: :day_id
        = form.collection_select(:day_id, @days, :id, :name, {prompt: "選択してください"}, {class: 'input-delivery-days__select'})


    .price
      %p.price__category-name 価格  (¥300 〜 9,999,999)

      .input-price
        .input-price__headline
          = form.label :price, "販売価格", class: 'input-price__headline--label'
          %span.input-price__headline--required 必須
          = render "error_form", culumn: :price
        = form.text_field :price, class: 'input-price__text-field'


    .submit
      = form.submit "出品する", class: 'submit__btn'

= render "users/footer"

app/views/items/search.html.haml
= render "header"

.cearch-contents
  .number-of-searches
    - if @items.length != 0
      .number-of-searches__true
        = "#{@items.length} 件の結果が見つかりました。"
    - else
      .number-of-searches__false
        該当する商品は見つかりませんでした。キーワードを変えて再度お試しください。

  .search-results
    - @items.each do |item|
      = link_to item_path(item), class: "search-item" do
        .search-item__display
          .search-item__display--price
            ¥
            = item.price.to_s(:delimited)
          = image_tag item.images[0].image.to_s, class: "search-item__display--image"
        .search-item__display--name
          = item.name
          
          

= render "footer"

app/views/items/show.html.haml
= render "header"

.item-details
  .item-details__flame
    .contents1
      - if @item.buyer_id.present?
        .item-sold
          売り切れました
      .item-name
        %h1 
        = @item.name
      .main
        .main__image
          .main__image__principal
            = image_tag @item.images[0].image.to_s, class: "image"
          .main__image__sub
            %ul.image__list
              - @item.images.each.with_index(1) do |image, i|
                - if i <= 4
                  %li.image__list__one
                    = image_tag image.image.to_s, class: "image"
          .main__image__sub
            %ul.image__list
              - @item.images.each.with_index(1) do |image, i|
                - if i >= 5 && i <= 8 
                  %li.image__list__one
                    = image_tag image.image.to_s, class: "image"
              -# 画像最大８枚以上の場合、「.main__image__sub」以下を後述する。
      .price
        .price-content
          .price-content__yen
            ¥
          .price-content__num
            = @item.price
        .price-incidental
          .price-incidental__tax
            （税込）
          .price-incidental__postage
            配送料
            = @delivery_fees.name

      .item-block
        .item-block__name
          = @item.name
      .details
        %table.details__table
          %tr.details__table__line
            %td.title 出品者
            %td.name 
              = @item.user.nickname
          %tr.details__table__line
            %td.title カテゴリー
            %td.name 
              - @category_parent_show.each do |parent|
                -if @item.category_id == parent.id
                  = link_to "#" do
                    = parent.name
                - parent.children.each do |child|
                  -if @item.category_id == child.id
                    = link_to "#" do
                      = parent.name
                      %br/
                    = link_to "#" do
                      = child.name
                  - child.children.each do |grandchild|
                    -if @item.category_id == grandchild.id
                      = link_to "#" do
                        = parent.name
                        %br/
                      = link_to "#" do
                        = child.name
                        %br/
                      = link_to "#" do
                        = grandchild.name

                
          %tr.details__table__line
            %td.title ブランド
            %td.name 
              = @item.brand
          %tr.details__table__line
            %td.title 状態
            %td.name
              = @conditions.name
          %tr.details__table__line
            %td.title サイズ
            %td.name
              = @item.size
          %tr.details__table__line
            %td.title 配送料負担
            %td.name
              = @delivery_fees.name
          %tr.details__table__line
            %td.title 発送方法
            %td.name 
              = @delivery_methods.name
          %tr.details__table__line
            %td.title 発送までの日数
            %td.name
              = @days.name
          %tr.details__table__line
            %td.title 発送元地域
            %td.name 
              -# リンク先未設定の為、”#”を仮記載
              = link_to "#" do
                = @prefectures.name

      .like
        - if user_signed_in?
          - if @item.user.id != current_user.id
            - if @like
              = link_to item_path, class: "like__click--none", remote: true do
                .like__click--none__icon
                  = icon('fas', 'star', class: 'icons')
                .like__click--none__letter
                  お気に入り済み

            - else
              = link_to item_path, class: "like__click", remote: true do
                .like__click__icon
                  = icon('fas', 'star', class: 'icons')
                .like__click__letter
                  お気に入り

            = link_to "#", class: "like__arart" do
              .like__arart__icon
                = icon('fas', 'flag', class: 'icons')
              .like__arart__letter
                不適切な商品の通報

    -# 売り切れかどうか？出品者か？などを条件分岐
    -if @item.buyer_id == nil
      - if user_signed_in? && current_user.id == @item.user.id
        .contents2
          = link_to edit_item_path(@item) , class: "item-purchase" do
            編集画面に進む
        .contents2
          = link_to item_path(@item), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "item-purchase" do
            この出品商品を削除する
      - elsif user_signed_in?
        .contents2
          = link_to item_purchases_path(@item, destination_id: @destination.id) , class: "item-purchase" do
            購入画面に進む
      - else
        .contents2
          = link_to new_user_session_path, class: "item-purchase" do
            購入画面に進む前に、ログインページへ
    
    -else
      - if user_signed_in? && current_user.id == @item.user.id
        .contents2
          = link_to item_path(@item) ,method: :delete, data: {confirm: "本当に削除しますか？"}, class: "item-purchase" do
            この出品商品を削除する
      - else 
        .contents2-sold
          .item-purchase
            この商品は既に購入されています
            
    .contents3
      -# コメント機能未実装の為、コメントアウト
      -# = form_with(model: [@item, @comment], local: true) do |f|
      = form_with(comment: @item, local: true) do |f|
        .new-comment
          = f.text_area :text, class: "new-comment__field"
          .caution
            %p
            相手のことを考え丁寧なコメントを心がけましょう。
            %br/
            不快な言葉遣いなどは利用制限や退会処分となることがあります。
          .comment
            = link_to "#" do
              %button{type: "submit", class:'btn'} 
                .comment__btn
                  = icon('fas', 'comment', class: 'icons')
                  %p コメントする
    .contents4
      - if @item.previous.present?
        = link_to item_path(@item.previous.id) do
          .previous
            .previous__icon
              = icon('fas', 'angle-left', class: 'icons')
            .previous__content
              前の商品
      - else
        .none
      - if @item.next.present?
        = link_to item_path(@item.next.id) do
          .next
            .next__content
              次の商品 
            .next__icon
              = icon('fas', 'angle-right', class: 'icons')
      - else 
        .none 
    .contents5
      .category-more
        -# カテゴリー機能が未実装の為、リンク先は”＃”で仮記載
        = link_to "#" do
          「カテゴリー名」をもっと見る
      .category-items
        - @category.items.each.with_index(1) do |item, i|
          - if item.id != @item.id && i <= 4
            .category-item
              = link_to item_path(item) do
                .category-item__first
                  .item-image
                    = image_tag item.images[0].image.to_s, class: "image"
                  .item-content
                    .item-content__name
                      = item.name
                    .item-content__mix
                      .item-content__mix__price
                        .item-content__mix__price__yen
                          ¥
                        .item-content__mix__price__num
                          = item.price
                      .item-content__mix__like
                        = icon('fas', 'star', class: 'icons')
                    .item-content__tax
                      （税込）

= render "footer"

= link_to new_item_path do
  .exhibit
    %p.exhibit--text 出品する
    = image_tag "icon/icon_camera.png",class: 'exhibit--image', width: "55px";

app/views/items/update.html.haml
= render "users/header"

.main
  .main__form
    .main__form__contents1
      .main__form__contents1__title
        更新が完了しました。
      = link_to root_path do
        トップページに戻る

= render "users/footer" 