config/routes.rb
Rails.application.routes.draw do
  root "items#index"
  
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  } 
   
  devise_scope :user do
    get 'users/confirmation' => 'users/registrations#confirmation'
  end

  resources :users do
    collection do
      get :logout, :like
    end
  end
  resources :items do
    collection do
      get :search
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
      get :header_category, defaults: { format: 'json' }
    end
    resource :likes, only: [:create, :destroy]
    resources :purchases do
      collection do
        get :purchase, :after_purchase
      end
    end
    member do
      get :image_delete
    end
  end
  resources :cards do
    collection do
      get :delete
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :payjp_key
  before_action :set_user
  before_action :header_category_parent, only: :index

  def index
    @category_parent = Category.roots
    if @user.card
      customer = Payjp::Customer.retrieve(@user.card.customer_id)
      cards = customer.cards
      if cards.data[0]
        @cards = cards
      end
    end
  end
  
  def create
    begin
      token = Payjp::Token.create({
        :card => {
          :number => params[:number],
          :cvc => params[:cvc],
          :exp_month => params[:exp_month],
          :exp_year => params[:exp_year]
        }},
        {
          'X-Payjp-Direct-Token-Generate': 'true'
        } 
      )
      unless @user.card
        customer = Payjp::Customer.create(
          card: token.id
        )
        card = Card.new(user_id: @user.id, customer_id: customer.id)
        card.save
        redirect_to action: :index
        flash[:notice] = '登録されました'
      else
        customer = Payjp::Customer.retrieve(@user.card.customer_id)
        customer.cards.create(
          card: token.id
        )
        redirect_to action: :index
        flash[:notice] = '登録されました'
      end
    rescue
      redirect_to action: :index
      flash[:alert] = '登録できませんでした　内容に誤りがあります'
    end
  end

  def delete
    customer = Payjp::Customer.retrieve(@user.card.customer_id)
    card = customer.cards.retrieve(params[:card_id])
    card.delete
    redirect_to action: :index
    flash[:alert] = '削除しました'
  end

  def header_category_parent
    @header_category_parent = Category.roots
  end
  private

  def payjp_key
    require 'payjp'
    Payjp.api_key = Rails.application.credentials.PAYJP[:secret_access_key]
  end

  def set_user
    @user = User.find(current_user.id)
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/index.html.haml
= render "items/header"

.wrapper
  = render "users/left-content"
  .card

    .card-content1
      .card-content1__head
        クレジットカード情報入力
      .card-content1__form
        = form_with url: {controller: 'cards', action: 'create' }, local: true do |f|
          .card-content1__number
            %label.card-content1__content--font
              カード番号
            %span.card-content1__content--required
              必須
            .card-content1__number--form
              = f.text_field :number, class: "number"
            .card-content1__number--card-icon
              = image_tag 'icon/card.png', size: '280x26';
          .card-content1__limit
            %label.card-content1__content--font
              有効期限
            %span.card-content1__content--required
              必須
            .card-content1__limit--form
              .card-content1__limit--form--month
                = f.select :exp_month, ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"]
                %span
                  月
              .card-content1__limit--form--year
                = f.select :exp_year, ["2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030"]
                %span
                  年
          .card-content1__security-code
            %label.card-content1__content--font
              セキュリティコード
            %span.card-content1__content--required
              必須
            .card-content1__security-code--form
              = f.text_field :cvc, class: 'security_code'
            .card-content1__security-code--info
              %span.card-content1__security-code--info--question
                ？
              カード裏面の番号とは？
          .card-content1__submit
            .card-content1__submit--form
              = f.submit "追加する", class: 'submit__btn'
    .card-content2
      .card_list
        .card_list__head
          クレジットカード一覧

        - if @cards
          - @cards.each do |card|
            .card_list__content
              .card_list__content--cover
                = link_to delete_cards_path(card_id: card.id) do
                  %span.card_list__content__btn
                    削除する
                .card_list__content__number
                  ************
                  = card.last4
                .card_list__content__limit
                  = card.exp_month
                  \/
                  = card.exp_year
                .card_list__content__brand
                  = card.brand
        - else
          .card-content1__none
            登録がありません

= render "items/footer"